kb-dk/ds-datahandler

- src/main/java/dk/kb/datahandler/util/CallbackReplacer.java
- src/main/java/dk/kb/datahandler/util/XMLEscapeSanitiser.java
- src/test/java/dk/kb/datahandler/oai/InvalidXmlTest.java
Added a general replacer and a specific replacer for XML-escapes and connected it to the InvalidXmlTest
> Illegal XML character escape handling

- pom.xml
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/oai/OaiJobCache.java
- src/test/java/dk/kb/datahandler/facade/DsDatahandlerFacadeTest.java
> Only have one job running for same target

- Jenkinsfile
- pom.xml
- src/main/java/dk/kb/datahandler/api/v1/impl/DsDatahandlerApiServiceImpl.java
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/oai/OaiHarvestClient.java
- src/main/openapi/ds-datahandler_v1.yaml
New service method to ingest records into ds-storage from a zip-file containing multiple file entries that each is a XML file with a single record.
> Finished zip-ingest

- src/main/java/dk/kb/datahandler/api/v1/impl/DsDatahandlerApiServiceImpl.java
- src/main/openapi/ds-datahandler_v1.yaml
> Add ping endpoint

- conf/ds-datahandler-behaviour.yaml
- pom.xml
- src/main/java/dk/kb/datahandler/config/ServiceConfig.java
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/test/java/dk/kb/datahandler/storageclient/StorageClientIntegrationTest.java
Switched to ds-storage autogenerated client dependency
> Switched to ds-storage autogenerated client dependency

- README.md
- pom.xml
- src/main/java/dk/kb/datahandler/api/v1/impl/DsDatahandlerApiServiceImpl.java
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/oai/OaiResponseFiltering.java
- src/main/openapi/ds-datahandler-openapi_v1.yaml
Make pvica filtering only apply to pvica OAI-harvests. 
Also spottet some leftover recordBases, which i've changed to origin
> Disc 208 target specific logic

- pom.xml
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/oai/OaiHarvestClient.java
- src/main/java/dk/kb/datahandler/oai/OaiResponseFiltering.java
- src/test/java/dk/kb/datahandler/pvica/PvicaDataTest.java
remove filter for preservica collections
> Disc 334 remove collection filtering

- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
> Correct ds-present param 'collection' to 'origin'

- src/main/java/dk/kb/datahandler/config/ServiceConfig.java
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/oai/OaiResponseFilterPreservica.java
- src/main/openapi/ds-datahandler-openapi_v1.yaml
- src/test/java/dk/kb/datahandler/facade/DsDatahandlerFacadeTest.java
- src/test/java/dk/kb/datahandler/oai/OaiHarvestClientIntegrationTest.java
- src/test/java/dk/kb/datahandler/pvica/PvicaDataTest.java
- src/test/resources/xml/pvica_origin_radio_manifestation.xml
- src/test/resources/xml/pvica_origin_tv_manifestation.xml
This PR splits records from preservica into two origins `radio` and `tv`. 
Hopefully we are at a solid solution now
> Disc 497 set origin for pvica

- CHANGELOG.md
- conf/ds-datahandler-behaviour.yaml
- pom.xml
- src/main/java/dk/kb/datahandler/api/v1/impl/DsDatahandlerApiServiceImpl.java
- src/main/java/dk/kb/datahandler/config/ServiceConfig.java
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/util/HttpPostUtil.java
- src/main/openapi/ds-datahandler-openapi_v1.yaml
Very straightforward use of streaming client.
Added optional mTime parametere to solrIndex method.
> DISC-521 implemented

- CHANGELOG.md
- src/main/java/dk/kb/datahandler/oai/OaiHarvestClient.java
Pvica basic authentication in every single call
> basic authentication in every single call

- conf/ds-datahandler-behaviour.yaml
- pom.xml
- src/main/templates/api.mustache
This **should** work without any changes to unit tests or external behaviour. It has not been deployed on devel.
> Port dependency bumps and mustache change from java-webapp-template

- pom.xml
- src/main/java/dk/kb/datahandler/webservice/ContextListener.java
- src/main/resources/logback.xml
> logback fix

- pom.xml
- src/main/java/dk/kb/datahandler/util/SolrUtils.java
The skeleton for delivering Pagin-Header-Count when indexing had already been made. This PR Updates dependencies to make it work. 
I've locally indexed and the value seems to come through correctly.
> Disc 657 paging record count

- .gitignore
- src/test/bin/oai_harvest.sh
Simple OAI-PMH test script tailored for testing a local Preservica installation at the Royal Danish Library. Not intended for general use.
> OAI-PMH test script

- src/main/openapi/ds-datahandler-openapi_v1.yaml
last one
can be tested by the endpoint `/solr/index`
> remove enum

- src/main/java/dk/kb/datahandler/oai/OaiResponseFilterPreservica.java
> fix wrong non-formatted regex

- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
Changed from ContinuationStream to ContinuationInputStream, which makes it possible to handle more data by paging through it. The previous implementation did not like to process 600K records at once
Furthermore this speeds up the process to 25 records pr second running in parallel.
> Updated streaming to use paging.

- src/main/java/dk/kb/datahandler/api/v1/impl/DsDatahandlerApiServiceImpl.java
- src/main/java/dk/kb/datahandler/config/ServiceConfig.java
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/kaltura/KalturaUploadClient.java
- src/main/java/dk/kb/datahandler/oai/OaiHarvestClient.java
- src/main/java/dk/kb/datahandler/oai/OaiResponseFilterPreservicaFive.java
- src/main/java/dk/kb/datahandler/oai/OaiResponseFilterPreservicaSeven.java
- src/main/java/dk/kb/datahandler/solr/SolrResponseHeader.java
- src/main/java/dk/kb/datahandler/util/HarvestTimeUtil.java
- src/main/java/dk/kb/datahandler/util/HttpPostUtil.java
- src/main/java/dk/kb/datahandler/util/SolrUtils.java
- src/test/java/dk/kb/datahandler/kaltura/KalturaUploadFolderIntegrationTest.java
- src/test/java/dk/kb/datahandler/kaltura/KalturaUploadIntegrationTest.java
Simple PR which updates logging messages and exceptions thrown throughout the Datahandler Facade with emphasis on making it clear which systems the exceptions are originating from.
> Dra 253 improve logging

- CHANGELOG.md
- src/main/java/dk/kb/datahandler/oai/OaiResponseFilterPreservicaSeven.java
- src/test/java/dk/kb/datahandler/oai/PreservicaFilterTest.java
Add correct origin filter for DOMS records
> Dra 903 correct filter

- CHANGELOG.md
- conf/ds-datahandler-behaviour.yaml
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/oai/OaiResponseFilterDrArchive.java
- src/main/java/dk/kb/datahandler/oai/OaiResponseFilterPreservicaSeven.java
- src/main/openapi/ds-datahandler-openapi_v1.yaml
- src/test/java/dk/kb/datahandler/oai/PreservicaFilterTest.java
Implement DR filter and change regex for origin detection to catch all weird DOMS namespaces
> Dra 729 implement dr filter

- pom.xml
- src/test/java/dk/kb/datahandler/kaltura/KalturaManualDeleteJob.java
New manual job method. Delete streams+metadata for entries in kaltura.
> DRA-138 manual delete job.

- CHANGELOG.md
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/preservica/client/DsPreservicaClient.java
- src/main/java/dk/kb/datahandler/webservice/ContextListener.java
- src/test/java/dk/kb/datahandler/preservica/PreservicaClientTest.java
Tiny PR moving initialization of Preservica Client into the method using it instead of on startup
> Dra 1119 move preservica access

- CHANGELOG.md
- conf/ds-datahandler-behaviour.yaml
- pom.xml
- src/main/java/dk/kb/datahandler/api/v1/impl/DsDatahandlerApiServiceImpl.java
- src/main/java/dk/kb/datahandler/api/v1/impl/ServiceApiServiceImpl.java
- src/main/java/dk/kb/datahandler/webservice/KBAuthorization.java
- src/main/java/dk/kb/datahandler/webservice/KBAuthorizationInterceptor.java
- src/main/java/dk/kb/datahandler/webservice/KBOAuth2Handler.java
- src/main/openapi/ds-datahandler-openapi_v1.yaml
- src/main/templates/api.mustache
- src/main/templates/apiServiceImpl.mustache
No method has OAuth enabled yet.
> Dra 439 enable oauth2

- CHANGELOG.md
- conf/ds-datahandler-behaviour.yaml
- conf/ds-datahandler-environment.yaml.SAMPLE
- pom.xml
- src/main/java/dk/kb/datahandler/config/ServiceConfig.java
- src/main/java/dk/kb/datahandler/util/SolrUtils.java
- src/test/java/dk/kb/datahandler/oai/OaiHarvestClientIntegrationTest.java
- src/test/java/dk/kb/datahandler/solr/SuggestIntegrationTest.java
Buyild solr suggest index after finished indexing and change SolrHttpClient to new SolrJdkHttpClient.
Tested with local solr and seems to build the index correctly.
> Dra 300 builds solr suggest index after finished indexing

- CHANGELOG.md
- pom.xml
- src/main/java/dk/kb/datahandler/enrichment/DataEnricher.java
- src/main/java/dk/kb/datahandler/enrichment/FragmentsClient.java
- src/test/java/dk/kb/datahandler/enrichment/FragmentClientTest.java
Håndter fejl i berigelsen bedre.
Nedgradering af saxon.
> Dra 1261 throw internal server exception on enrich error

- CHANGELOG.md
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/preservica/PreservicaManifestationExtractor.java
- src/main/java/dk/kb/datahandler/preservica/client/DsPreservicaClient.java
- src/main/java/dk/kb/datahandler/util/PreservicaUtils.java
- src/test/java/dk/kb/datahandler/preservica/PreservicaClientTest.java
- src/test/java/dk/kb/datahandler/preservica/client/PreservicaClientTest.java
> Retry manifestation lookup

- CHANGELOG.md
- src/test/java/dk/kb/datahandler/kaltura/GenerateKalturaUploadXmlFromSolrDocs.java
- src/test/java/dk/kb/datahandler/kaltura/KalturaItemXml.java
- src/test/resources/kaltura/kaltura_item.xml
Added manual batch job to create bulk upload XML for Kaltura from solr documents json. There are 3 cases for how to create the ftp download.
bart-tv
bart-radio
kuana/preservica (here extension .mp3 or .mp4 must be added)
> Dra 710 make kaltura xml from solr

- src/main/java/dk/kb/datahandler/api/v1/impl/DsDatahandlerApiServiceImpl.java
- src/main/openapi/ds-datahandler-openapi_v1.yaml
Remove unused mTimeFrom for solr index open API.
Long parameter gave nullpointer.
> Remove unused mTimeFrom for solr index

- CHANGELOG.md
- pom.xml
Fix multiple import except the ones from kaltura client where the native kaltura client contains the same dependencies from different libraries...
> fix imports from most locations

- CHANGELOG.md
- src/main/java/dk/kb/datahandler/util/SolrUtils.java
Name of branch is not correct, since the error was not in the datahandler.
This PR only fixes that suggest index only build if there was new documents indexed.
> Only build suggest index if there was indexed any documents

- CHANGELOG.md
- pom.xml
> Dra 222 undersøg inline view

- conf/ds-datahandler-behaviour.yaml
> Changed APIException to be handled

- Jenkinsfile
Removes artifacts from jenkins, because the server is lacking in space
> DRA-2011-remove-artifacts-from-jenkins
