- CHANGELOG.md
- DEVELOPER.md
- README.md
- conf/ds-datahandler-behaviour.yaml
- pom.xml
Same procedure as for ds-storage: Change the default port from 8080 to 9071. This pull request also updates the ds-storage port in the provided configuration from 8080 to 9072.
> Switch from jetty port 8080 to 9071

- conf/ds-datahandler.logback.xml
Prepending the artifact to logback.xml makes it clear which project it belongs to, when deployed to a server with multiple services.
Concurrently support has been added to [aegis](https://github.com/kb-dk/aegis/) so that `kb deploy devel` works for `ds-datahandler`.
> Rename logback.xml and make it log to file

- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
Extremely small pull request: Simple log change to show the full recordId when ingesting a record, for easier copy-pasting when debugging
> Change logging for ZIP upload to log the full recordId instead of just the UUID

- conf/ds-datahandler-behaviour.yaml
- pom.xml
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/api/index.html
This pull request renames the  `pvica.devel`-base to the more telling `ds.radiotv` and fixes an unrelated bug where renaming of the OpenAPI YAML causes a missing file.
> Rename radiotv-base and fix OpenAPI-problem

- conf/ds-datahandler-behaviour.yaml
- pom.xml
- src/main/java/dk/kb/datahandler/api/v1/impl/DsDatahandlerApiServiceImpl.java
- src/main/java/dk/kb/datahandler/config/ServiceConfig.java
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/util/HttpPostUtil.java
- src/main/openapi/ds-datahandler-openapi_v1.yaml
Workflow calling ds-present that will call ds-storage and xslt-transform the documents into solr documents.
The call is not done by openAPI client since it does not return an inputstream.
The input stream is given directly to a POST request to the solr-server so it is not in memory.
The unused ds-present  client is added to the pom.xml and sample code is uncommented.
> Disc 282 storage2solr

- pom.xml
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/oai/OaiHarvestClient.java
- src/main/java/dk/kb/datahandler/oai/OaiResponseFiltering.java
- src/main/openapi/ds-datahandler-openapi_v1.yaml
After a full ingest, delete old records in storage that are earlier than those ingested. Doing this AFTER the ingest and not before, will mean that the storage will be functionable during the ingest.
> After a full ingest, delete old records in storage that are earlier than

- CHANGELOG.md
- conf/ds-datahandler-behaviour.yaml
- pom.xml
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
With HTTP simulated authentication token support added to `ds-present`, `ds-datahandler` should also have that enabled.
This pull request adds a tiny bit of code for sending the `Simulated-OAuth2-Group: internal_service` header. This is synchronized with `aegis` being updated to set the header for the devel deploy of `ds-datahandler`.
Also, and sorry for the messy unmess, there are multiple minor corrections to log calls. The only real code change is [line 111 in DsDatahandlerFacade](https://github.com/kb-dk/ds-datahandler/compare/DISC-542_simulate_oauth?expand=1#diff-abd474d163b4b58635205cdccde637a799dfcaa3c814c60aa758b57498ea75faR111).
> Simulated OAuth

- src/test/bin/oai_harvest.conf.template
- src/test/bin/oai_harvest.sh
Each individual call to the OAI-PMH server is now times, to check how much time is spend on the initial call vs. subsequent calls.
> Add timing information for each OAI-PMH call

- conf/ds-datahandler-behaviour.yaml
- pom.xml
- src/main/java/dk/kb/datahandler/api/v1/impl/DsDatahandlerApiServiceImpl.java
- src/main/java/dk/kb/datahandler/config/ServiceConfig.java
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/oai/OaiFromUntilInterval.java
- src/main/java/dk/kb/datahandler/oai/OaiHarvestClient.java
- src/main/java/dk/kb/datahandler/oai/OaiJobCache.java
- src/main/java/dk/kb/datahandler/oai/OaiResponseFilterPreservica.java
- src/main/java/dk/kb/datahandler/util/HarvestTimeUtil.java
- src/main/openapi/ds-datahandler-openapi_v1.yaml
- src/test/java/dk/kb/datahandler/oai/OaiHarvestClientIntegrationTest.java
- src/test/java/dk/kb/datahandler/pvica/PvicaDataTest.java
- src/test/java/dk/kb/datahandler/util/HarvestTimeUtilTest.java
Pvica now always batch 1 day at a time and always use ISO date format. (since it gives the most results...)
The datestamp return from pvica that is saved in last harvest time file will also be reformatted from ISO+millis to ISO.
If the day only format is given it will be reformatted to ISO date. The reverse situation happens for our own COP harvesting. The "fixing" code is done same place.
Code changes:
OAI target (yaml configuration) has two new attributes 
day_only:  If true the harvest will always be batched in days.
start_day: If defined this will be first harvest day, also for full import. This is to avoid killing Sigfreds machines when starting full import from API page.
The full import method will now identify OAI targets with day_only and batch them instead.
> Disc 775 pvica oai from until day only

- src/main/java/dk/kb/datahandler/api/v1/impl/ServiceApiServiceImpl.java
- src/main/openapi/ds-datahandler-openapi_v1.yaml
Deployed on devel11
Extract the job list from the status method into a new method that only return jobs.
New jobs method can be testet on openAPI or by calling: http://devel11:10001/ds-datahandler/v1/monitor/jobs
(I started two jobs so list is not empty)
Status method (now without jobs):
http://devel11:10001/ds-datahandler/v1/monitor/status
> Commit of DISC-831. Split status and job list into two methods

- CHANGELOG.md
- pom.xml
- src/test/java/dk/kb/datahandler/kaltura/KalturaUploadFolderIntegrationTest.java
- src/test/java/dk/kb/datahandler/kaltura/KalturaUploadIntegrationTest.java
- src/test/java/dk/kb/datahandler/oai/InvalidXmlTest.java
- src/test/java/dk/kb/datahandler/oai/OaiHarvestClientIntegrationTest.java
- src/test/java/dk/kb/datahandler/storageclient/StorageClientIntegrationTest.java
- src/test/java/dk/kb/datahandler/util/DsDatahandlerClientTest.java
DRA-103 implemented. Integration tag for unittests.
POM parent upgraded to v25 that supports the new tags 'blocked' and 'integration'. 
'integration' tag added to two unittests.
> DRA-103 implemented. Integration tag for unittests.

- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/oai/OaiHarvestClient.java
- src/main/java/dk/kb/datahandler/oai/OaiResponseFilterPreservicaFive.java
- src/main/java/dk/kb/datahandler/oai/OaiResponseFilterPreservicaSeven.java
- src/main/java/dk/kb/datahandler/oai/OaiResponseFilterPreserviceSeven.java
- src/main/openapi/ds-datahandler-openapi_v1.yaml
- src/test/java/dk/kb/datahandler/oai/OaiHarvestClientIntegrationTest.java
- src/test/java/dk/kb/datahandler/pvica/PvicaDataTest.java
Refactoring of `OaiResponseFilter`. The old implementation didn't really make use of the way we're supporting multiple filters. I've renamed the old `OaiResponseFilterPreservica` to `OaiResponseFilterPreservicaFive` and then created a new filter where the logic for Preservica 7 has been moved to.
As we are moving towards a preservica 7 world, I've chosen to let the filter in YAML files specified as: `filter: preservica` reference the newly added `OaiResponseFilterPreservicaSeven` class and introduced a `filter: preservica5` for backwards compatibility. 
While testing this filtering locally on jetty, with a local ds-storage. I've stumpled upon an error when harvesting from preservica. I get an `HTTP 401`-error with the comment: _WWW-Authenticate header missing for response code 401_. …
> Dra 400 check filter for preservica7

- src/test/bin/oai_harvest.sh
UNTIL parameter optional.
Easy to test
FROM=2025-01-01T00:00:00Z UNTIL=2026-01-01T00:00:00Z ./oai_harvest.sh
and
FROM=2025-01-01T00:00:00Z ./oai_harvest.sh
The log will show the server url call.
> DRA-185 UNTIL parameter is changed to optional

- pom.xml
- src/main/java/dk/kb/datahandler/util/HttpPostUtil.java
- src/main/java/dk/kb/datahandler/util/SolrUtils.java
More logging: 
Implements the ability to log a warning when the size of the stream being indexed to solr is suspeciously tiny. (I've chosen the limit of 1000 bytes pr record. The average size of solr documents when indexing today is somewhere between 1400 and 1800 bytes.
> Dra 900 Add more logging when indexing to solr

- CHANGELOG.md
- src/main/java/dk/kb/datahandler/preservica/PreservicaManifestationExtractor.java
- src/main/java/dk/kb/datahandler/preservica/client/DsPreservicaClient.java
- src/main/java/dk/kb/datahandler/util/PreservicaUtils.java
- src/test/java/dk/kb/datahandler/preservica/PreservicaClientTest.java
When no ContentObject has been found for record. An identifier lookup is made to see if the record is a DOMS record. If yes, the id is used as referenceId.
One question for you: Should the referenceId be appended with either .mp4 or .mp3 or are these values not added to the files in kaltura. They are present in the filenames on our server.
> Dra 1102 update manifestation enrichment with DOMS ids

- CHANGELOG.md
- pom.xml
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/preservica/PreservicaManifestationExtractor.java
- src/main/java/dk/kb/datahandler/util/PreservicaUtils.java
- src/test/java/dk/kb/datahandler/preservica/PreservicaClientTest.java
- src/test/java/dk/kb/datahandler/util/PreservicaUtilTest.java
Changed storage method used in methods not working with record.data. 
deployed on devel. Tested the kaltura endpoint, needing the list of records, works as intended.
> Change storage client method used in methods not requiring record.data

- CHANGELOG.md
- pom.xml
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/test/java/dk/kb/datahandler/kaltura/KalturaManualDeleteJob.java
- src/test/java/dk/kb/datahandler/kaltura/KalturaManualFileUploader.java
- src/test/java/dk/kb/datahandler/kaltura/KalturaUploadFolderIntegrationTest.java
Use kaltura app-tokens instead of mastersecret. Upgraded ds-kaltura  to v.1.2.4.
Reads two new properties:
kaltura.token
kaltura.tokenId
Mastersecret can be leaved blank.
> Use kaltura appTokens instead of mastersecret.

- CHANGELOG.md
- src/main/java/dk/kb/datahandler/facade/DsDatahandlerFacade.java
- src/main/java/dk/kb/datahandler/preservica/client/DsPreservicaClient.java
- src/main/java/dk/kb/datahandler/util/PreservicaUtils.java
- src/test/java/dk/kb/datahandler/preservica/client/PreservicaClientTest.java
This was supposed to only be a pull request on making log messages more telling for the manifestation enrichment endpoint. However the recent events of slow crunch time made me look into some performance as well. I believe I've found a bit of a performance increase. Compared to master, this branch runs the added test approx. 20% faster. I also made sure that opened and used inputstream were indeed correctly closed. Memory usage for manifestation enrichment seems to spike less as well, se attached pictures:
**Memory usage for profiling test on master**
**Memory usage for profiling test on this branch**
> Dra 1371 better manifestation logging and performance boost in enrichment endpoint

- CHANGELOG.md
- src/main/java/dk/kb/datahandler/kaltura/KalturaDeltaUploadJob.java
For Kaltura upload check on storage record if it already has a kaltura id, since there is a delay in kaltura from when records are searchable
> For Kaltura upload check on storage record if it already has a kaltura

- CHANGELOG.md
- conf/ds-datahandler-behaviour.yaml
- src/main/java/dk/kb/datahandler/config/ServiceConfig.java
- src/main/java/dk/kb/datahandler/kaltura/KalturaDeltaUploadJob.java
ds-kaltura is build to take a secret if present. However, ds-datahandler sets adminSecret to null no matter what. This PR changes this so that the adminSecret can be added to the conf environment yaml as a failsafe if appToken sessions ever fails again.
This change is related to DRA-1950
> Dra 1950 admin secret as failsafe
